"""Security detection rules as pure data, kept separate so patterns are easy to review."""
import re


SECURITY_RULES = [
    {
        "pattern": r'subprocess\.(?:run|call|Popen|check_output)\(.*shell=True.*\)',
        "description": "Command Injection Risk (shell=True)",
        "explanation": "Using shell=True invokes a real shell. If any part of the command is user-controlled, attackers can inject additional shell syntax to execute arbitrary commands.",
        "severity": "Critical",
        "category": "Command Injection",
        "cwe": "CWE-78",
        "owasp": "A03:2021-Injection",
        "remediation": "Avoid shell=True with untrusted input. Pass arguments as a list, validate/escape inputs, or use high-level APIs instead of spawning shells.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": r'os\.system\s*\(',
        "description": "Command Execution via os.system",
        "explanation": "os.system executes commands through a shell. If the command contains untrusted data, it can lead to command injection. Prefer subprocess with a list of args and without shell=True.",
        "severity": "High",
        "category": "Command Injection",
        "cwe": "CWE-78",
        "owasp": "A03:2021-Injection",
        "remediation": "Replace os.system with subprocess.run([...]) without shell=True and ensure all inputs are validated or hard-coded.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": r'os\.popen\s*\(',
        "description": "Command Execution via os.popen",
        "explanation": "os.popen runs a shell command and captures output. If any part of the command is user-controlled, this can lead to command injection.",
        "severity": "High",
        "category": "Command Injection",
        "cwe": "CWE-78",
        "owasp": "A03:2021-Injection",
        "remediation": "Avoid os.popen for executing commands. Use subprocess APIs with argument lists and remove direct concatenation of user input into commands.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": re.compile(r"\.execute\([^\)]*(select|insert|update|delete)[^\)]*\+\s*", re.IGNORECASE),
        "description": "Possible SQL Injection (string concatenation)",
        "explanation": "Building SQL queries via string concatenation allows attackers to inject arbitrary SQL when untrusted input is concatenated into the query. Use parameterized queries instead.",
        "severity": "High",
        "category": "SQL Injection",
        "cwe": "CWE-89",
        "owasp": "A03:2021-Injection",
        "remediation": "Use parameterized queries / prepared statements. Never concatenate untrusted input directly into SQL strings.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": r"\.execute\([^\)]*%s[^\)]*%[^\)]*\)",
        "description": "Possible SQL Injection (percent formatting)",
        "explanation": "Using %s-style string formatting to build SQL queries can allow injection if untrusted data is interpolated. Use parameterized queries provided by the DB driver.",
        "severity": "High",
        "category": "SQL Injection",
        "cwe": "CWE-89",
        "owasp": "A03:2021-Injection",
        "remediation": "Avoid %-style string formatting for SQL. Use placeholders supported by the DB driver and pass parameters separately.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": re.compile(r"\.execute\(\s*f['\"](select|insert|update|delete).*{[^}]+}.*['\"]\s*\)", re.IGNORECASE),
        "description": "Possible SQL Injection (f-string)",
        "explanation": "Using f-strings to interpolate variables directly into SQL statements can lead to SQL injection. Use bind parameters / placeholders instead.",
        "severity": "High",
        "category": "SQL Injection",
        "cwe": "CWE-89",
        "owasp": "A03:2021-Injection",
        "remediation": "Do not format SQL using f-strings. Switch to parameterized queries and bind variables instead of interpolating them.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": re.compile(r"\.execute\(\s*['\"].*(select|insert|update|delete).*['\"]\s*\.format\(", re.IGNORECASE),
        "description": "Possible SQL Injection (.format)",
        "explanation": "Using .format() on SQL strings can allow injection when untrusted values are formatted into the query. Prefer parameterized queries.",
        "severity": "High",
        "category": "SQL Injection",
        "cwe": "CWE-89",
        "owasp": "A03:2021-Injection",
        "remediation": "Avoid using .format() to build SQL. Use placeholders (e.g. ? or %s) and pass user input as separate parameters.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": re.compile(r"\b\w+\s*=\s*['\"].*(select|insert|update|delete).*['\"]\s*\+\s*", re.IGNORECASE),
        "description": "Possible SQL Injection (query concatenation)",
        "explanation": "Building SQL query variables via string concatenation allows injection before execution. Use parameterized queries with placeholders and bind values separately.",
        "severity": "High",
        "category": "SQL Injection",
        "cwe": "CWE-89",
        "owasp": "A03:2021-Injection",
        "remediation": "Do not concatenate user-controlled values into SQL query variables. Use parameterized SQL and pass parameters separately to execute().",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": re.compile(r"\b\w+\s*=\s*['\"].*(select|insert|update|delete).*['\"]\s*%\s*\(", re.IGNORECASE),
        "description": "Possible SQL Injection (query percent formatting)",
        "explanation": "Using %-formatting to build SQL query variables can allow injection when untrusted data is interpolated.",
        "severity": "High",
        "category": "SQL Injection",
        "cwe": "CWE-89",
        "owasp": "A03:2021-Injection",
        "remediation": "Avoid %-formatting for SQL query variables. Use parameter placeholders and pass values as a separate argument tuple/list.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": re.compile(r"\b\w+\s*=\s*f['\"].*(select|insert|update|delete).*\{[^}]+\}.*['\"]", re.IGNORECASE),
        "description": "Possible SQL Injection (query f-string)",
        "explanation": "Using f-strings to build SQL query variables with interpolated values can enable SQL injection.",
        "severity": "High",
        "category": "SQL Injection",
        "cwe": "CWE-89",
        "owasp": "A03:2021-Injection",
        "remediation": "Do not interpolate variables into SQL f-strings. Use parameterized queries and bind variables safely.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": re.compile(r"\b\w+\s*=\s*['\"].*(select|insert|update|delete).*['\"]\s*\.format\(", re.IGNORECASE),
        "description": "Possible SQL Injection (query .format)",
        "explanation": "Using .format() to build SQL query variables can allow injection when values are inserted into SQL text.",
        "severity": "High",
        "category": "SQL Injection",
        "cwe": "CWE-89",
        "owasp": "A03:2021-Injection",
        "remediation": "Avoid .format() for SQL string construction. Use prepared statements and bind parameters separately.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": r'eval\s*\(',
        "description": "Use of eval",
        "explanation": "eval() executes arbitrary expressions. If tainted input reaches eval, it enables arbitrary code execution. Use safe parsers or explicit whitelists.",
        "severity": "High",
        "category": "Dynamic Code Execution",
        "cwe": "CWE-94",
        "owasp": "A03:2021-Injection",
        "remediation": "Avoid eval on dynamic input. Use safe parsers (e.g. ast.literal_eval) or explicit allowlists of operations.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": r'exec\s*\(',
        "description": "Use of exec",
        "explanation": "exec() executes arbitrary Python code. If untrusted input reaches exec, it enables arbitrary code execution. Avoid exec; refactor to safer alternatives.",
        "severity": "High",
        "category": "Dynamic Code Execution",
        "cwe": "CWE-94",
        "owasp": "A03:2021-Injection",
        "remediation": "Refactor code to avoid exec. Use functions, mappings or plugins instead of executing constructed code strings.",
        "confidence": "High",
        "pci_dss": "6.5.1",
        "nist": "SI-10",
    },
    {
        "pattern": r'pickle\.load',
        "description": "Unsafe Deserialization (pickle.load)",
        "explanation": "Untrusted pickle data can execute code during loading. Use safer formats (e.g., JSON) for untrusted inputs.",
        "severity": "High",
        "category": "Deserialization",
        "cwe": "CWE-502",
        "owasp": "A08:2021-Software and Data Integrity Failures",
        "remediation": "Do not use pickle for untrusted data. Prefer JSON/MsgPack with strict schema validation and type checks.",
        "confidence": "High",
        "pci_dss": "6.5.6",
        "nist": "SI-10",
    },
    {
        "pattern": r'yaml\.load\s*\(',
        "description": "Unsafe YAML load",
        "explanation": "yaml.load without SafeLoader can construct arbitrary objects. Use yaml.safe_load or specify SafeLoader.",
        "severity": "High",
        "category": "Deserialization",
        "cwe": "CWE-502",
        "owasp": "A08:2021-Software and Data Integrity Failures",
        "remediation": "Use yaml.safe_load with SafeLoader (or FullLoader with caution) when parsing untrusted YAML content.",
        "confidence": "Medium",
        "pci_dss": "6.5.6",
        "nist": "SI-10",
    },
    {
        "pattern": r'hashlib\.(md5|sha1)\s*\(',
        "description": "Weak Cryptography (MD5/SHA1)",
        "explanation": "MD5/SHA-1 are considered broken for security-sensitive contexts. Use SHA-256 or stronger (and HMAC/AEAD where appropriate).",
        "severity": "Medium",
        "category": "Weak Cryptography",
        "cwe": "CWE-327",
        "owasp": "A02:2021-Cryptographic Failures",
        "remediation": "Replace MD5/SHA-1 with modern hashes like SHA-256 and use HMAC/AEAD modes where appropriate.",
        "confidence": "High",
        "pci_dss": "4.1",
        "nist": "SC-13",
    },
    {
        "pattern": r'(?:Crypto\.Cipher\.DES\b|DES\.new\s*\()',
        "description": "Weak Cipher (DES)",
        "explanation": "DES is obsolete and insecure due to short key length. Use AES-GCM/ChaCha20-Poly1305.",
        "severity": "Medium",
        "category": "Weak Cryptography",
        "cwe": "CWE-327",
        "owasp": "A02:2021-Cryptographic Failures",
        "remediation": "Migrate from DES to a modern cipher such as AES-GCM or ChaCha20-Poly1305 with strong keys.",
        "confidence": "High",
        "pci_dss": "4.1",
        "nist": "SC-13",
    },
    {
        "pattern": r'(?:Crypto\.Cipher\.ARC4\b|ARC4\.new\s*\()',
        "description": "Weak Cipher (RC4/ARC4)",
        "explanation": "RC4/ARC4 are considered insecure due to multiple cryptographic weaknesses. Avoid RC4 and use modern AEAD ciphers instead.",
        "severity": "Medium",
        "category": "Weak Cryptography",
        "cwe": "CWE-327",
        "owasp": "A02:2021-Cryptographic Failures",
        "remediation": "Avoid RC4/ARC4 and use modern AEAD ciphers (AES-GCM, ChaCha20-Poly1305) provided by well-maintained libraries.",
        "confidence": "High",
        "pci_dss": "4.1",
        "nist": "SC-13",
    },
    {
        "pattern": r'(?i)(api[_-]?key|secret|password|token)\s*[:=]\s*["\"][^"\"]{6,}["\"]',
        "description": "Hardcoded Secret",
        "explanation": "Hardcoding credentials risks accidental leakage and compromise. Move secrets to a secure vault or environment variables.",
        "severity": "High",
        "category": "Secrets & Keys",
        "cwe": "CWE-798",
        "owasp": "A02:2021-Cryptographic Failures",
        "remediation": "Remove hardcoded secrets from source code. Load them from a secure secrets manager or environment variables.",
        "confidence": "Medium",
        "pci_dss": "8.2.1",
        "nist": "IA-5",
        "gdpr": "Article 32",
    },
    {
        "pattern": r'AKIA[0-9A-Z]{16}',
        "description": "Potential AWS Access Key",
        "explanation": "String matches AWS access key pattern. Treat as secret and rotate if exposed.",
        "severity": "High",
        "category": "Secrets & Keys",
        "cwe": "CWE-798",
        "owasp": "A02:2021-Cryptographic Failures",
        "remediation": "Rotate the exposed AWS access key immediately and move credentials to a dedicated secrets management system.",
        "confidence": "Medium",
        "pci_dss": "8.2.1",
        "nist": "IA-5",
        "gdpr": "Article 32",
    },
    {
        "pattern": r'-----BEGIN RSA PRIVATE KEY-----',
        "description": "Hardcoded Private Key",
        "explanation": "Embedding private keys directly in source code risks key leakage and long-term compromise. Use secure key management instead.",
        "severity": "Critical",
        "category": "Secrets & Keys",
        "cwe": "CWE-522",
        "owasp": "A02:2021-Cryptographic Failures",
        "remediation": "Remove private keys from the repository. Store them in a secure key vault and reference them via configuration only.",
        "confidence": "High",
        "pci_dss": "3.5",
        "nist": "SC-12",
        "gdpr": "Article 32",
    },
    {
        "pattern": r'(os\.remove|os\.unlink|shutil\.rmtree)\s*\(',
        "description": "Destructive Filesystem Operation",
        "explanation": "Deleting files/directories based on untrusted paths can enable path traversal or data loss. Validate and constrain paths.",
        "severity": "Medium",
        "category": "Filesystem Access",
        "cwe": "CWE-22",
        "owasp": "A01:2021-Broken Access Control",
        "remediation": "Validate and normalize filesystem paths, restrict deletions to allowed directories, and avoid using untrusted input directly in file APIs.",
        "confidence": "Medium",
        "pci_dss": "6.5.8",
        "nist": "AC-3",
    },
    {
        "pattern": r'open\s*\(.*?,\s*["\"][wa]["\"]',
        "description": "File Write Operation",
        "explanation": "Writing to files using unvalidated user-controlled paths can lead to overwrites or injection. Validate paths and use secure directories.",
        "severity": "Medium",
        "category": "Filesystem Access",
        "cwe": "CWE-22",
        "owasp": "A01:2021-Broken Access Control",
        "remediation": "Ensure file paths are validated, constrained to specific directories, and not constructed directly from untrusted user input.",
        "confidence": "Low",
        "pci_dss": "6.5.8",
        "nist": "AC-3",
    },
    {
        "pattern": r'"\.\./',
        "description": "Potential Path Traversal (relative path)",
        "explanation": "Using ../ in paths can indicate directory traversal. When combined with untrusted input, this can allow access outside intended directories.",
        "severity": "Medium",
        "category": "Path Traversal",
        "cwe": "CWE-22",
        "owasp": "A01:2021-Broken Access Control",
        "remediation": "Normalize and validate paths, strip ../ sequences, and use safe join functions to prevent escaping the intended directory.",
        "confidence": "Low",
        "pci_dss": "6.5.8",
        "nist": "AC-3",
    },
    {
        "pattern": r'zipfile\.ZipFile\s*\(',
        "description": "Zip Processing (check for Zip Slip)",
        "explanation": "Extracting archives without validating file paths can lead to Zip Slip, where files are written outside the intended directory.",
        "severity": "Medium",
        "category": "Filesystem Access",
        "cwe": "CWE-22",
        "owasp": "A01:2021-Broken Access Control",
        "remediation": "Validate each member path in archives before extraction and prevent files from writing outside the target directory.",
        "confidence": "Low",
        "pci_dss": "6.5.8",
        "nist": "AC-3",
    },
    {
        "pattern": r'requests\.(get|post|put|delete)\s*\(.*http://',
        "description": "HTTP Request without TLS",
        "explanation": "Using plain HTTP instead of HTTPS can expose sensitive data to interception and tampering. Prefer HTTPS endpoints whenever possible.",
        "severity": "Medium",
        "category": "Network / Exfiltration",
        "cwe": "CWE-319",
        "owasp": "A02:2021-Cryptographic Failures",
        "remediation": "Use HTTPS for all sensitive traffic and update endpoints to enforce TLS with strong cipher suites.",
        "confidence": "High",
        "pci_dss": "4.1",
        "nist": "SC-8",
    },
    {
        "pattern": r'requests\.(get|post|put|delete)\s*\([^\)]*verify\s*=\s*False',
        "description": "TLS Verification Disabled",
        "explanation": "Disabling TLS certificate verification exposes connections to man-in-the-middle attacks. Only disable verification for controlled debugging scenarios.",
        "severity": "High",
        "category": "Network / Exfiltration",
        "cwe": "CWE-295",
        "owasp": "A02:2021-Cryptographic Failures",
        "remediation": "Do not set verify=False in production. Configure proper CA bundles and validate certificates for all outbound HTTPS requests.",
        "confidence": "High",
        "pci_dss": "4.1",
        "nist": "SC-8",
    },
    {
        "pattern": r'requests\.(get|post|put|delete)\s*\(.*https?://',
        "description": "Outbound HTTP Request",
        "explanation": "Outbound HTTP requests may exfiltrate data or contact untrusted services. Ensure endpoints are trusted and inputs are validated.",
        "severity": "Low",
        "category": "Network / Exfiltration",
        "cwe": "CWE-200",
        "owasp": "A01:2021-Broken Access Control",
        "remediation": "Restrict outbound HTTP calls to approved domains and validate all request parameters before sending.",
        "confidence": "Low",
        "pci_dss": "1.3",
        "nist": "SC-7",
    },
    {
        "pattern": r'socket\.socket\s*\(',
        "description": "Raw Socket Usage",
        "explanation": "Low-level socket usage can bypass higher-level security controls. Carefully validate destinations, ports, and data.",
        "severity": "Low",
        "category": "Network / Exfiltration",
        "cwe": "CWE-200",
        "owasp": "A05:2021-Security Misconfiguration",
        "remediation": "Wrap raw socket usage with validation logic, restrict remote endpoints, and consider higher-level protocols with built-in security.",
        "confidence": "Low",
        "pci_dss": "1.3",
        "nist": "SC-7",
    },
]
